# Generated by Django 5.2 on 2025-05-05 11:54

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('references', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Delivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата изменения')),
                ('number', models.CharField(max_length=100, unique=True, verbose_name='Номер')),
                ('departure_time', models.DateTimeField(verbose_name='Время отправления')),
                ('arrival_time', models.DateTimeField(verbose_name='Время прибытия')),
                ('distance', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Дистанция (км)')),
                ('condition', models.CharField(choices=[('Исправно', 'Исправно'), ('Неисправно', 'Неисправно')], default='Исправно', max_length=20, verbose_name='Техническое состояние')),
                ('media_file', models.FileField(blank=True, null=True, upload_to='delivery_files/%Y/%m/', verbose_name='Медиа-файл')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Примечания')),
                ('cargo_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='references.cargotype', verbose_name='Тип груза')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='core_created_deliveries', to=settings.AUTH_USER_MODEL, verbose_name='Кем создано')),
                ('packaging', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='references.packagingtype', verbose_name='Упаковка')),
                ('services', models.ManyToManyField(blank=True, to='references.service', verbose_name='Услуги')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='references.deliverystatus', verbose_name='Статус')),
                ('transport_model', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='references.transportmodel', verbose_name='Модель транспорта')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='core_updated_deliveries', to=settings.AUTH_USER_MODEL, verbose_name='Кем изменено')),
            ],
            options={
                'verbose_name': 'Доставка',
                'verbose_name_plural': 'Доставки',
                'ordering': ['-departure_time'],
            },
        ),
    ]
